# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Microblaze_Block_Design/Microblaze_Block_Design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_Block_Design || ORIG_REF_NAME==Microblaze_Block_Design} -quiet] -quiet

# IP: bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_clk_wiz_0_0/Microblaze_Block_Design_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_Block_Design_clk_wiz_0_0 || ORIG_REF_NAME==Microblaze_Block_Design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_microblaze_0_0/Microblaze_Block_Design_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_Block_Design_microblaze_0_0 || ORIG_REF_NAME==Microblaze_Block_Design_microblaze_0_0} -quiet] -quiet

# IP: bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_mdm_1_0/Microblaze_Block_Design_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_Block_Design_mdm_1_0 || ORIG_REF_NAME==Microblaze_Block_Design_mdm_1_0} -quiet] -quiet

# IP: bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_rst_clk_wiz_0_100M_0/Microblaze_Block_Design_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_Block_Design_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==Microblaze_Block_Design_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_axi_uartlite_0_0/Microblaze_Block_Design_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_Block_Design_axi_uartlite_0_0 || ORIG_REF_NAME==Microblaze_Block_Design_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_microblaze_0_axi_periph_0/Microblaze_Block_Design_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_Block_Design_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Microblaze_Block_Design_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_dlmb_v10_0/Microblaze_Block_Design_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_Block_Design_dlmb_v10_0 || ORIG_REF_NAME==Microblaze_Block_Design_dlmb_v10_0} -quiet] -quiet

# IP: bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_ilmb_v10_0/Microblaze_Block_Design_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_Block_Design_ilmb_v10_0 || ORIG_REF_NAME==Microblaze_Block_Design_ilmb_v10_0} -quiet] -quiet

# IP: bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_dlmb_bram_if_cntlr_0/Microblaze_Block_Design_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_Block_Design_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Microblaze_Block_Design_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_ilmb_bram_if_cntlr_0/Microblaze_Block_Design_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_Block_Design_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Microblaze_Block_Design_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_lmb_bram_0/Microblaze_Block_Design_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_Block_Design_lmb_bram_0 || ORIG_REF_NAME==Microblaze_Block_Design_lmb_bram_0} -quiet] -quiet

# IP: bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodTMP3_0_2/Microblaze_Block_Design_PmodTMP3_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_Block_Design_PmodTMP3_0_2 || ORIG_REF_NAME==Microblaze_Block_Design_PmodTMP3_0_2} -quiet] -quiet

# IP: bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_xbar_0/Microblaze_Block_Design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_Block_Design_xbar_0 || ORIG_REF_NAME==Microblaze_Block_Design_xbar_0} -quiet] -quiet

# IP: bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_axi_gpio_0_0/Microblaze_Block_Design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_Block_Design_axi_gpio_0_0 || ORIG_REF_NAME==Microblaze_Block_Design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_axi_intc_0_0/Microblaze_Block_Design_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_Block_Design_axi_intc_0_0 || ORIG_REF_NAME==Microblaze_Block_Design_axi_intc_0_0} -quiet] -quiet

# IP: bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodDPG1_0_0/Microblaze_Block_Design_PmodDPG1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_Block_Design_PmodDPG1_0_0 || ORIG_REF_NAME==Microblaze_Block_Design_PmodDPG1_0_0} -quiet] -quiet

# XDC: bd/Microblaze_Block_Design/Microblaze_Block_Design_ooc.xdc
