package view;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import java.util.Arrays;
import javax.swing.*;
import javax.swing.event.*;

public class LoginView extends JFrame {
    private JLabel jcomp2;
    private JTextField usernameTF;
    private JLabel jcomp4;
    private JPasswordField passwordTF;
    private JButton loginBTN;
    private JButton registerBTN;

    public LoginView() {
        //construct components
        jcomp2 = new JLabel ("Username:");
        usernameTF = new JTextField (5);
        jcomp4 = new JLabel ("Password:");
        passwordTF = new JPasswordField (5);
        loginBTN = new JButton ("Login");
        registerBTN = new JButton ("Register");

        //adjust size and set layout
        setPreferredSize (new Dimension (280, 190));
        setLayout (null);

        //add components
        add (jcomp2);
        add (usernameTF);
        add (jcomp4);
        add (passwordTF);
        add (loginBTN);
        add (registerBTN);

        //set component bounds (only needed by Absolute Positioning)
        jcomp2.setBounds (25, 30, 100, 25);
        usernameTF.setBounds (95, 30, 145, 25);
        jcomp4.setBounds (25, 65, 100, 25);
        passwordTF.setBounds (95, 65, 145, 25);
        loginBTN.setBounds (25, 105, 100, 25);
        registerBTN.setBounds (140, 105, 100, 25);

        setTitle("Delivey Service Login");
        setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        pack();
        setVisible(true);
    }

    public void addLoginListener(ActionListener a) {
        loginBTN.addActionListener(a);
    }

    public void addRegisterListener(ActionListener a) {
        registerBTN.addActionListener(a);
    }

    public void displayMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    public String getUsername() {
        return usernameTF.getText();
    }

    public char[] getPassword() {
        return passwordTF.getPassword();
    }


}

