# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Hp/Desktop/an II/sem II/AC/Projects/mips_single_cycle_v2/mips_single_cycle_v2.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Hp/Desktop/an II/sem II/AC/Projects/mips_single_cycle_v2/mips_single_cycle_v2.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Hp/Desktop/an II/sem II/AC/Projects/mips_single_cycle_v2/mips_single_cycle_v2.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Hp/Desktop/an II/sem II/AC/Projects/mips_single_cycle_v2/mips_single_cycle_v2.srcs/sources_1/new/DataMemory.vhd}
  {C:/Users/Hp/Desktop/an II/sem II/AC/Projects/mips_single_cycle_v2/mips_single_cycle_v2.srcs/sources_1/new/MonoPulse.vhd}
  {C:/Users/Hp/Desktop/an II/sem II/AC/Projects/mips_single_cycle_v2/mips_single_cycle_v2.srcs/sources_1/new/InstuctionFetch.vhd}
  {C:/Users/Hp/Desktop/an II/sem II/AC/Projects/mips_single_cycle_v2/mips_single_cycle_v2.srcs/sources_1/new/InstructionDecode.vhd}
  {C:/Users/Hp/Desktop/an II/sem II/AC/Projects/mips_single_cycle_v2/mips_single_cycle_v2.srcs/sources_1/new/ExecutionUnit.vhd}
  {C:/Users/Hp/Desktop/an II/sem II/AC/Projects/mips_single_cycle_v2/mips_single_cycle_v2.srcs/sources_1/new/ControlUnit.vhd}
  {C:/Users/Hp/Desktop/an II/sem II/AC/Projects/mips_single_cycle_v2/mips_single_cycle_v2.srcs/sources_1/new/Display.vhd}
  {C:/Users/Hp/Desktop/an II/sem II/AC/Projects/mips_single_cycle_v2/mips_single_cycle_v2.srcs/sources_1/new/test_env.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Hp/Desktop/an II/sem II/AC/Baysis 3 - Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Hp/Desktop/an II/sem II/AC/Baysis 3 - Master.xdc}}]


synth_design -top test_env -part xc7a35tcpg236-1


write_checkpoint -force -noxdef test_env.dcp

catch { report_utilization -file test_env_utilization_synth.rpt -pb test_env_utilization_synth.pb }
