# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/pault/Desktop/semI/SSC/Microblaze/Microblaze.srcs/sources_1/bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodTMP3_0_2/Microblaze_Block_Design_PmodTMP3_0_2.xci
# IP: The module: 'Microblaze_Block_Design_PmodTMP3_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/pault/Desktop/semI/SSC/Microblaze/Microblaze.srcs/sources_1/bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodTMP3_0_2/src/PmodTMP3_axi_iic_0_0/PmodTMP3_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodTMP3_axi_iic_0_0 || ORIG_REF_NAME==PmodTMP3_axi_iic_0_0} -quiet] -quiet

# IP: c:/Users/pault/Desktop/semI/SSC/Microblaze/Microblaze.srcs/sources_1/bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodTMP3_0_2/src/PmodTMP3_pmod_bridge_0_0/PmodTMP3_pmod_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodTMP3_pmod_bridge_0_0 || ORIG_REF_NAME==PmodTMP3_pmod_bridge_0_0} -quiet] -quiet

# IP: c:/Users/pault/Desktop/semI/SSC/Microblaze/Microblaze.srcs/sources_1/bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodTMP3_0_2/src/PmodTMP3_xlconstant_0_0/PmodTMP3_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodTMP3_xlconstant_0_0 || ORIG_REF_NAME==PmodTMP3_xlconstant_0_0} -quiet] -quiet

# XDC: c:/Users/pault/Desktop/semI/SSC/Microblaze/Microblaze.srcs/sources_1/bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodTMP3_0_2/src/PmodTMP3_axi_iic_0_0/PmodTMP3_axi_iic_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodTMP3_axi_iic_0_0 || ORIG_REF_NAME==PmodTMP3_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/pault/Desktop/semI/SSC/Microblaze/Microblaze.srcs/sources_1/bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodTMP3_0_2/src/PmodTMP3_axi_iic_0_0/PmodTMP3_axi_iic_0_0_ooc.xdc

# XDC: c:/Users/pault/Desktop/semI/SSC/Microblaze/Microblaze.srcs/sources_1/bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodTMP3_0_2/Microblaze_Block_Design_PmodTMP3_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Microblaze_Block_Design_PmodTMP3_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/pault/Desktop/semI/SSC/Microblaze/Microblaze.srcs/sources_1/bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodTMP3_0_2/src/PmodTMP3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Microblaze_Block_Design_PmodTMP3_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/pault/Desktop/semI/SSC/Microblaze/Microblaze.srcs/sources_1/bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodTMP3_0_2/src/PmodTMP3_pmod_bridge_0_0/PmodTMP3_pmod_bridge_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodTMP3_pmod_bridge_0_0 || ORIG_REF_NAME==PmodTMP3_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/pault/Desktop/semI/SSC/Microblaze/Microblaze.srcs/sources_1/bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodTMP3_0_2/src/PmodTMP3_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# IP: c:/Users/pault/Desktop/semI/SSC/Microblaze/Microblaze.srcs/sources_1/bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodTMP3_0_2/Microblaze_Block_Design_PmodTMP3_0_2.xci
# IP: The module: 'Microblaze_Block_Design_PmodTMP3_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/pault/Desktop/semI/SSC/Microblaze/Microblaze.srcs/sources_1/bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodTMP3_0_2/src/PmodTMP3_axi_iic_0_0/PmodTMP3_axi_iic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodTMP3_axi_iic_0_0 || ORIG_REF_NAME==PmodTMP3_axi_iic_0_0} -quiet] -quiet

# IP: c:/Users/pault/Desktop/semI/SSC/Microblaze/Microblaze.srcs/sources_1/bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodTMP3_0_2/src/PmodTMP3_pmod_bridge_0_0/PmodTMP3_pmod_bridge_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodTMP3_pmod_bridge_0_0 || ORIG_REF_NAME==PmodTMP3_pmod_bridge_0_0} -quiet] -quiet

# IP: c:/Users/pault/Desktop/semI/SSC/Microblaze/Microblaze.srcs/sources_1/bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodTMP3_0_2/src/PmodTMP3_xlconstant_0_0/PmodTMP3_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodTMP3_xlconstant_0_0 || ORIG_REF_NAME==PmodTMP3_xlconstant_0_0} -quiet] -quiet

# XDC: c:/Users/pault/Desktop/semI/SSC/Microblaze/Microblaze.srcs/sources_1/bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodTMP3_0_2/src/PmodTMP3_axi_iic_0_0/PmodTMP3_axi_iic_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodTMP3_axi_iic_0_0 || ORIG_REF_NAME==PmodTMP3_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/pault/Desktop/semI/SSC/Microblaze/Microblaze.srcs/sources_1/bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodTMP3_0_2/src/PmodTMP3_axi_iic_0_0/PmodTMP3_axi_iic_0_0_ooc.xdc

# XDC: c:/Users/pault/Desktop/semI/SSC/Microblaze/Microblaze.srcs/sources_1/bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodTMP3_0_2/Microblaze_Block_Design_PmodTMP3_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Microblaze_Block_Design_PmodTMP3_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/pault/Desktop/semI/SSC/Microblaze/Microblaze.srcs/sources_1/bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodTMP3_0_2/src/PmodTMP3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Microblaze_Block_Design_PmodTMP3_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/pault/Desktop/semI/SSC/Microblaze/Microblaze.srcs/sources_1/bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodTMP3_0_2/src/PmodTMP3_pmod_bridge_0_0/PmodTMP3_pmod_bridge_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodTMP3_pmod_bridge_0_0 || ORIG_REF_NAME==PmodTMP3_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/pault/Desktop/semI/SSC/Microblaze/Microblaze.srcs/sources_1/bd/Microblaze_Block_Design/ip/Microblaze_Block_Design_PmodTMP3_0_2/src/PmodTMP3_pmod_bridge_0_0/src/pmod_concat_ooc.xdc
